server:
  port: 8080
  servlet:
    contextPath: /${spring.application.name}/v1

spring:
  application:
    name: mssivimss-oauth-online
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url:  jdbc:mysql://10.102.44.18:3306/SIVIBDDS  #jdbc:mysql://10.102.44.18:3306/SIVIBDDS #${msit_CONNECTION_DB} jdbc:mariadb://localhost:3306/SIVIBDDS #
    username: SIVI_USER #SIVI_USER #${msit_USERNAME_DB}
    password: 51V1_US3R #Maria2023 #51V1_US3R #${msit_PASSWORD_DB}
    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      #max-lifetime:  ${msit_LIFE_TIME}
      #idle-timeout:  ${msit_TIME_OUT}
      #connection-timeout: ${msit_CONNECTION_TIMEOUT}
      auto-commit: false
      #maximum-pool-size:  ${msit_CONNECTION_POOL}
      #minimum-idle:  ${msit_CONNECTION_IDLE}

  main:
    allow-circular-references: true
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
           
logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error

endpoints:
   envio-correo: "https://sivimss-ds.apps.ocp.imss.gob.mx/mssivimss-ser-externos/v1/catalogos/externos/enviar/correo/recuperacontrasenia" #"http://serviciosdigitalesinterno-stage.imss.gob.mx/serviciosDigitales-rest/v1/util/correoElectronico/enviar"
   consulta-siap: "http://serviciosdigitalesinterno-stage.imss.gob.mx/serviciosDigitales-rest/v1/externos/siap/matricula/"
   renapo: "http://serviciosdigitalesinterno-stage.imss.gob.mx/serviciosDigitales-rest/v1/externos/renapo/curp/"
jwt:
  secretkey: funcionamuybienlogin
  secretkey-flujo: funcionamuybien
  secretkey-dominios: funcionamuybiendominio
  expiration-milliseconds: '360'
  
management:
      endpoints:
          web:
            exposure:
                include:
                    health,info,metrics


resilience4j.circuitbreaker:
  circuitBreakerAspectOrder: 1
  instances:
    msflujo:
      automaticTransitionFromOpenToHalfOpenEnabled: "true"
      failureRateThreshold: '50'
      slidingWindowType: COUNT_BASED
      event-consumer-buffer-size: '10'
      registerHealthIndicator: 'true'
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: '3'
      slidingWindowSize: '5'
resilience4j.retry:
    retryAspectOrder: 2
    instances:
        msflujo:
           maxAttempts: 3 #${msit_NUMERO_INTENTOS}
           waitDuration: 5s #${msit_TIEMPO_DURACION}
resilience4j.timelimiter:
    timeLimiterAspectOrder: 3
    instances:
      msflujo:
        timeout-duration: 3s
        
#formato_fecha: '%d/%m/%Y'
formato_fecha_hora: '%d/%m/%Y %H:%i:%s'
patron_formato_fecha_hora: 'dd/MM/yyyy HH:mm:ss'
ruta-log: '/sivimss-files/log/'
tiempo-vida: 10